# Generated by Django 3.2 on 2021-04-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40)),
                ('needUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserUIPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('UserUIConnect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userui')),
            ],
        ),
    ]
